apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rhrz80bky-go-gitops
  description: This is GitOps manifest for rhrz80bky-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rhrz80bky-go
    backstage.io/kubernetes-id: rhrz80bky-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rhrz80bky-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rhrz80bky-go
