apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhrz80bky-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhrz80bky-go 
  name: rhrz80bky-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhrz80bky-go
    weight: 100 
