apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhrz80bky-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhrz80bky-go 
  name: rhrz80bky-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhrz80bky-go 
